[package]
name = "chronicle_commander"
version = "0.1.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]

[dependencies]
chronicle_persistence = { version = "0.1.0", path = "../chronicle_persistence" }
futures = "0.1.9"
